use cars;
-- READ DATA --
SELECT * FROM CARS_DEKHO;

-- TOTAL CARS --
SELECT COUNT(*) FROM CARS_DEKHO;

-- THE MANAGER ASKED THE EMPLOYEEE HOW MANY CARS WILL BE AVAILABLE IN 2023? --
 SELECT COUNT(*) FROM CARS_DEKHO WHERE YEAR = 2023;
 
 -- THE MANAGER ASKED THE EMPLOYEE HOW MANY CARS IS AVAILABLE IN 2020,2021,2022? --
 SELECT YEAR , COUNT(*) FROM CARS_DEKHO WHERE YEAR IN (2020,2021,2022) GROUP BY YEAR;
 
 -- CLIENT ASKED ME TO PRINT THE TOTAL OF ALL CARS BY YEAR --
 SELECT YEAR ,COUNT(*) FROM CARS_DEKHO GROUP BY YEAR;
 
 --  CLIENT ASKED TO CAR DEALER AGENT HOW MANY DIESEL CARS WILL BE THERE IN 2020? --
 SELECT COUNT(*) FROM CARS_DEKHO WHERE FUEL = "DIESEL" AND YEAR = 2020;
 
 --  CLIENT ASKED TO CAR DEALER AGENT HOW MANY PETROL CARS WILL BE THERE IN 2020? --
 SELECT COUNT(*) FROM CARS_DEKHO WHERE FUEL = "PETROL" AND YEAR = 2020;

-- THE MANAGER TOLD THE EMPLOYEE TO GIVE A PRINT ALL THE FUEL DIESEL || PETROL || CNG || CARS COME BY ALL TEAR --
SELECT YEAR , COUNT(*) FROM CARS_DEKHO WHERE FUEL = 'DIESEL' GROUP BY YEAR;
SELECT YEAR , COUNT(*) FROM CARS_DEKHO WHERE FUEL = 'PETROL' GROUP BY YEAR;
SELECT YEAR , COUNT(*) FROM CARS_DEKHO WHERE FUEL = 'CNG' GROUP BY YEAR;
-- ALL FUEL CARS (COMBINING ALL FUEL CARS) --
SELECT YEAR , COUNT(*) FROM CARS_DEKHO WHERE FUEL IN ('DIESEL','PETROL','CNG') GROUP BY YEAR;

-- MANAGER SAID THERE WERE MORE THAN 500 CARS IN A GIVEN YEAR, WHICH YEAR HAD MORE THAN 100 CARS? --
SELECT YEAR , COUNT(*) FROM CARS_DEKHO GROUP BY YEAR HAVING COUNT(*) > 500; 

-- MANAGER SAID THERE WERE LESS THAN 100 CARS IN A GIVEN YEAR, WHICH YEAR HAD MORE THAN 100 CARS? --
SELECT YEAR , COUNT(*) FROM CARS_DEKHO GROUP BY YEAR HAVING COUNT(*) < 100; 

-- THE MANAGER SAID TO THE EMPLOYEE ALL CARS COUNT DETAILS BETWEEN 2015 AND 2023; WE NEED A CMPLETE LIST --
SELECT COUNT(*) FROM CARS_DEKHO WHERE YEAR BETWEEN 2015 AND 2023;

-- THE MANAGER SAID TO THE EMPLOYEE ALL CARS  DETAILS BETWEEN 2015 AND 2023; WE NEED A CMPLETE LIST --
SELECT * FROM CARS_DEKHO WHERE YEAR BETWEEN 2015 AND 2023;

-- END --






















